### ISSUE TITLE
Validations issue with profile_name

### ISSUE THREAD

**Issue by a-a-ron** [a-a-ron/jibjabber#1]
When i put validations for profile_name, such as `presence, uniqueness and format`, my test fails because my @message returns an empty {}. Without the validations, i can register a new user without problem. This is expected since no validations present, but once i include the validations, a new user registering can't register even if their credentials are validated. 

I'm pretty sure my validations and test are written properly, so i'm thinking it's an error somewhere else. Anyway, below are my validations and test for `profile_name`.

![screen shot 2015-10-29 at 9 42 27 am](https://cloud.githubusercontent.com/assets/6351798/10823460/702dc796-7e21-11e5-991f-d71f273e556b.png)
![screen shot 2015-10-29 at 9 42 38 am](https://cloud.githubusercontent.com/assets/6351798/10823463/72a7e736-7e21-11e5-8b4c-7dc51e66b4fd.png)

Here is the result after clicking "sign up" when trying to register a new user. I don't know why i'm getting these three errors. I'm putting in a new profile_name and formatting it correctly.
![screen shot 2015-10-29 at 9 47 55 am](https://cloud.githubusercontent.com/assets/6351798/10823658/37832e8a-7e22-11e5-8b8c-2cb5a6bb5e09.png)

Here is the test result that fails 
![screen shot 2015-10-29 at 10 02 55 am](https://cloud.githubusercontent.com/assets/6351798/10824064/6101a6e0-7e24-11e5-9926-d48ec09432f9.png)

@mattcantstop

**Comment by a-a-ron** [comment]
`UPDATE`: So, i changed the profile_name and email in my test and was able to get it to pass. However, registering a user in the application still responds the same. I knew the test wouldn't change the result, but now that it's passing, i'm curious on why the app is failing.
![screen shot 2015-10-29 at 10 34 47 am](https://cloud.githubusercontent.com/assets/6351798/10825078/0760841c-7e29-11e5-80cc-71e573681183.png)

**Comment by a-a-ron** [comment]
I think i figured it out. I included `profile_name` to the configure_permitted_parameters.
![screen shot 2015-10-29 at 11 28 15 am](https://cloud.githubusercontent.com/assets/6351798/10826625/50c97c2e-7e30-11e5-8e58-3706250c62b0.png)

**Comment by mattcantstop** [comment]
I assume you are using Devise? What does the sanitizer method do? I assume sanitize, but why would that make it fail?

**Comment by a-a-ron** [comment]
Yes, since i added profile_name to my model, i needed to add it here. This makes a little more sense https://github.com/plataformatec/devise#strong-parameters. I don't understand it completely, but it works.

**Comment by mattcantstop** [comment]
@a-a-ron, if it was a strong parameters issue than that makes sense. I didn't realize that method was doing strong parameters. 

Strong parameters are a way to whitelist parameters. Before strong parameters you could accidentally expose parameters of the model to be updated that you didn't want to be externally available. 

With strong parameters you deliberately put them into that method to demonstrate a desire to make them available to be manipulated. Let me know if you want me to explain it in person at some point. 

Read up some more on them [here](http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters).
